import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import HomeHero from '../components/templates/HomeHero/HomeHero';
import Navbar from '../components/organisms/Navbar/Navbar';
import HomeSubheading from '../components/templates/HomeSubheading/HomeSubheading';
import HomeAlternateSubheading from '../components/templates/HomeAlternateSubheading/HomeAlternateSubheading';
import HomeSecondarySubheading from '../components/templates/HomeSecondarySubheading/HomeSecondarySubheading';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeHero />
      <HomeSubheading />
      <HomeAlternateSubheading />
      <HomeSecondarySubheading />

      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
